apiVersion: v1
kind: ReplicationController
metadata:
  name: replica-nginx
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: temp-nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.1"
            memory: "150Mi"